##Ar Google all-genders - all countries

#google_feed_create_ar_all_gender.sql
#GOOGLE to ERP Mapping on Product
drop table if exists product_google_cat;
create table product_google_cat as select cpf.sku id, cat1.ID cat1,cat2.ID cat2,cat3.ID cat3, coalesce(map1.code, map2.code, map3.code, map4.code) google_cat_code, cat1.NAME_E cat1_name  from (select sku from catalog_product_flat_3 group by sku) as cpf LEFT JOIN (select PRODN, CAT1, CAT2, CAT3, CAT4 from ITEMS group by PRODN) i on i.PRODN=cpf.sku LEFT JOIN PRODUCT_CAT1 cat1 on i.CAT1=cat1.ID LEFT JOIN PRODUCT_CAT2 cat2 on i.CAT2=cat2.ID LEFT JOIN PRODUCT_CAT3 cat3 on i.CAT3=cat3.ID left join google_erp_category_mapping map1 on map1.cat1_id =  cat1.ID and map1.cat2_id =  cat2.ID and map1.cat3_id = cat3.ID left join google_erp_category_mapping map2 on  map2.cat1_id =  cat1.ID and map2.cat2_id =  cat2.ID  left join (select code,cat1_id from google_erp_category_mapping where cat2_id is NULL and cat3_id is NULL) map3 on map3.cat1_id =  cat1.ID left join google_erp_category_mapping map4 on map4.cat2_id =  cat2.ID GROUP BY cpf.sku;
create index product_google_cat_idx on product_google_cat (id);

DROP TABLE IF exists google_feed_sar_index;
create table google_feed_sar_index as select cpf.sku as `Id`, "Perfume Event" `ads_label`, "Perfume Event" `custom_label_0`
from perfume_sale_sku join (select sku, entity_id from catalog_product_flat_3 group by sku) as cpf on cpf.sku=perfume_sale_sku.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  where ci.stock_status=1; 
DROP TABLE IF exists google_feed_aed_index;
create table google_feed_aed_index as select cpf.sku as `Id`, "Perfume Event" `ads_label`, "Perfume Event" `custom_label_0`
from perfume_sale_sku join (select sku, entity_id from catalog_product_flat_3 group by sku) as cpf on cpf.sku=perfume_sale_sku.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  where ci.stock_status=1;

#KWD
#======
DROP TABLE IF exists google_feed_kwd_ar_all_gender;
create table google_feed_kwd_ar_all_gender as  
SELECT cpf.sku id, "1021268294" as mobile_ios_app_store_id, concat("boutiqaat://product_id/", cpf.entity_id) as mobile_ios_app_link, concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) as mobile_android_app_link, replace(cpf.name,'"','') as title, cpf.description as description, concat("https://www.boutiqaat.com/en-kw/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat(cpf.price, " KWD") price, concat(coalesce(cpf.special_price, cpf.price), " KWD") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, IF(length(trim(cpev.value)) in (8,12,13,14),"Yes","No") as identifier_exists, cpf.manufacturer_value as brand_name, 'new' as `condition`, (case when cpf.gender='4194' then "male" when cpf.gender='2741' then "female" else "unisex" end) as `gender` FROM catalog_product_flat_3 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="KWD" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code') GROUP BY cpf.sku ORDER BY cpf.entity_id ;	


#AED
#======
DROP TABLE IF exists google_feed_aed_ar_all_gender;
create table google_feed_aed_ar_all_gender as  
SELECT cpf.sku id, "1021268294" as mobile_ios_app_store_id, concat("boutiqaat://product_id/", cpf.entity_id) as mobile_ios_app_link, concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) as mobile_android_app_link, replace(cpf.name,'"','') as title, cpf.description as description, concat("https://www.boutiqaat.com/en-ae/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1,"in stock","out of stock") as availability, concat((FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0)), " AED") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " AED") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, IF(length(trim(cpev.value)) in (8,12,13,14),"Yes","No") as identifier_exists, cpf.manufacturer_value as brand_name, 'new' as `condition`, (case when cpf.gender='4194' then "male" when cpf.gender='2741' then "female" else "unisex" end) as `gender` FROM catalog_product_flat_3 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="AED" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code') GROUP BY cpf.sku ORDER BY cpf.entity_id ;	


#BHD
#======
DROP TABLE IF exists google_feed_bhd_ar_all_gender;
create table google_feed_bhd_ar_all_gender as  
SELECT cpf.sku id, "1021268294" as mobile_ios_app_store_id, concat("boutiqaat://product_id/", cpf.entity_id) as mobile_ios_app_link, concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) as mobile_android_app_link, replace(cpf.name,'"','') as title, cpf.description as description, concat("https://www.boutiqaat.com/en-bh/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat((FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0)), " BHD") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " BHD") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, IF(length(trim(cpev.value)) in (8,12,13,14),"Yes","No") as identifier_exists, cpf.manufacturer_value as brand_name, 'new' as `condition`, (case when cpf.gender='4194' then "male" when cpf.gender='2741' then "female" else "unisex" end) as `gender` FROM catalog_product_flat_3 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="BHD" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code') GROUP BY cpf.sku ORDER BY cpf.entity_id ;	

#OMR
#======
DROP TABLE IF exists google_feed_omr_ar_all_gender;
create table google_feed_omr_ar_all_gender as  
SELECT cpf.sku id, "1021268294" as mobile_ios_app_store_id, concat("boutiqaat://product_id/", cpf.entity_id) as mobile_ios_app_link, concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) as mobile_android_app_link, replace(cpf.name,'"','') as title, cpf.description as description, concat("https://www.boutiqaat.com/en-om/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat((FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0)), " OMR") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " OMR") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, IF(length(trim(cpev.value)) in (8,12,13,14),"Yes","No") as identifier_exists, cpf.manufacturer_value as brand_name, 'new' as `condition`, (case when cpf.gender='4194' then "male" when cpf.gender='2741' then "female" else "unisex" end) as `gender` FROM catalog_product_flat_3 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="OMR" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code') GROUP BY cpf.sku ORDER BY cpf.entity_id ;	

#QAR
#======
DROP TABLE IF exists google_feed_qar_ar_all_gender;
create table google_feed_qar_ar_all_gender as  
SELECT cpf.sku id, "1021268294" as mobile_ios_app_store_id, concat("boutiqaat://product_id/", cpf.entity_id) as mobile_ios_app_link, concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) as mobile_android_app_link, replace(cpf.name,'"','') as title, cpf.description as description, concat("https://www.boutiqaat.com/en-qa/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat((FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0)), " QAR") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " QAR") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, IF(length(trim(cpev.value)) in (8,12,13,14),"Yes","No") as identifier_exists, cpf.manufacturer_value as brand_name, 'new' as `condition`, (case when cpf.gender='4194' then "male" when cpf.gender='2741' then "female" else "unisex" end) as `gender` FROM catalog_product_flat_3 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="QAR" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code') GROUP BY cpf.sku ORDER BY cpf.entity_id ;	

#SAR
#======
DROP TABLE IF exists google_feed_sar_ar_all_gender;
create table google_feed_sar_ar_all_gender as  
SELECT cpf.sku id, "1021268294" as mobile_ios_app_store_id, concat("boutiqaat://product_id/", cpf.entity_id) as mobile_ios_app_link, concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) as mobile_android_app_link, replace(cpf.name,'"','') as title, cpf.description as description, concat("https://www.boutiqaat.com/en-sa/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat((FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0)), " SAR") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " SAR") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, IF(length(trim(cpev.value)) in (8,12,13,14),"Yes","No") as identifier_exists, cpf.manufacturer_value as brand_name, 'new' as `condition`, (case when cpf.gender='4194' then "male" when cpf.gender='2741' then "female" else "unisex" end) as `gender` FROM catalog_product_flat_3 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="SAR" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code') GROUP BY cpf.sku ORDER BY cpf.entity_id ;	

#USD
#======
DROP TABLE IF exists google_feed_usd_ar_all_gender;
create table google_feed_usd_ar_all_gender as  
SELECT cpf.sku id, "1021268294" as mobile_ios_app_store_id, concat("boutiqaat://product_id/", cpf.entity_id) as mobile_ios_app_link, concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) as mobile_android_app_link, replace(cpf.name,'"','') as title, cpf.description as description, concat("https://www.boutiqaat.com/en-kw/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat((FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0)), " USD") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " USD") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, IF(length(trim(cpev.value)) in (8,12,13,14),"Yes","No") as identifier_exists, cpf.manufacturer_value as brand_name, 'new' as `condition`, (case when cpf.gender='4194' then "male" when cpf.gender='2741' then "female" else "unisex" end) as `gender` FROM catalog_product_flat_3 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="USD" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code') GROUP BY cpf.sku ORDER BY cpf.entity_id  ;